baseURL = 'https://rubiagatra.github.io/'
languageCode = 'en-us'
title = 'Doni Rubiagatra'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Doni Rubiagatra Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am an Indonesian Software Engineer with a strong foundation in computer science 
and a passion for designing efficient, scalable systems. My expertise spans areas 
such as algorithms, distributed systems, databases, artificial intelligence, 
and I enjoy diving deep into emerging technologies to solve complex problems. 
"""


# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/rubiagatra"

[[params.social]]
name = "medium"
url = "https://medium.com/@rubiagatra"

[[params.social]]
name = "github"
url = "https://github.com/rubiagatra"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

